version: '3.1'

services:

  ovs:
    image: jaibw/api
    restart: always
    ports:
      - 8082:8081
    environment:
      DBHOST: postgres
      DBPORT: '5432'
      DATABASE: postgres
      DBUSER: postgres
      DBPASSWORD: password
    depends_on:
      - postgres

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - ovs-db:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8083:8080
    depends_on:
      - postgres

volumes:
    ovs-db:
