apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-NAME
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/NAME"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-NAME
  namespace: NAME
spec:
  volumeName: pv-NAME
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
